# Generated by Django 4.2.30 on 2026-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(choices=[('investor', 'Investor'), ('partner', 'Strategic Partner'), ('donor', 'Donor / Funder'), ('collaboration', 'Collaboration'), ('other', 'Other')], max_length=50)),
                ('donation_amount', models.CharField(blank=True, help_text='If donor, approximate amount in USD', max_length=100)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Interest Submission',
                'verbose_name_plural': 'Interest Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
