# Generated by Django 4.2.30 on 2026-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestsubmission',
            name='location',
            field=models.CharField(blank=True, help_text='City, country, or region', max_length=200),
        ),
    ]
